message: 'blogcrud dev-message'

spring:
   h2:
      console:
         enabled: true
         path: /h2-console
         
management:
  endpoints:
    web:
      exposure:
         include: '*' 
        
eureka:
   instance:
      # Prefer IP for containers, which don't have DNS
      preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
