message: 'userservice standard-message'

spring:   
   h2:
      console:
         enabled: true
         path: /h2-console
         
management:
  endpoints:
    web:
      exposure:
         include: '*'
         
eureka:
   instance:
      preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
         
